# DO NOT EDIT THIS FILE!
#
# Python module RenderFarm generated by omniidl

import omniORB
omniORB.updateModule("RenderFarm")

# ** 1. Stub files contributing to this module
import RenderFarm_idl

# ** 2. Sub-modules

# ** 3. End
