# DO NOT EDIT THIS FILE!
#
# Python module RenderFarm__POA generated by omniidl

import omniORB
omniORB.updateModule("RenderFarm__POA")

# ** 1. Stub files contributing to this module
import RenderFarm_idl

# ** 2. Sub-modules

# ** 3. End
